JSON importer
steview/mtgdb2 pull request #12
Opened 2017-02-24 13:52 UTC by ahmetabdi

2017-02-27 13:45 UTC, steview requested changes
Only one comment. Can we namespace the import please MTGDB::Importers::JSONImporter. WDYT?

2017-02-27 13:46 UTC, ahmetabdi commented
Sounds good to me I'll make that change

2017-03-04 22:40 UTC, steview requested changes

2017-03-04 22:40 UTC, steview commented on spec/lib/mtg_json_importer_spec.rb
> +    context 'given json for a set' do
I'm not sure we need contexts for this spec, I think it should be one scenario using the JSON data _with_ the card data. Maybe use describe blocks to neatly divide the set and card based specs. WDYT?

2017-03-06 08:53 UTC, ahmetabdi commented
Any idea why this doesn't work @steview 

Class:
`class MTGDB::Importers::JSONImporter`

Output:
`uninitialized constant MTGDB`

2017-03-06 12:25 UTC, steview commented
Is the directory structure correct? Are you including it correctly in the init?

2017-03-06 14:18 UTC, steview approved these changes

2017-03-06 14:18 UTC, merged